# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZejr2T-MsFu6EE8kGOlRej1GWSM72z2
"""

import pandas as pd
baza={
    "FISH":[ "Shokirjonov.S.Sh","Yuzupova.Z.M","Shokirjonov.A.Sh","Shokirjonova.Sh.Sh","Muhamadaliyev.Q.S","Shokirjonova.D.M","Rahmonaliyeva.M.F","Yusupov.Sh.M","Rahmonaliyev.S.F","Yusuopova.J.Sh"],
    "YOSHI":[ '20','39','8','16','20','16','20','3','17','36' ],
    "MAKTABI":['53-maktab','53-maktab','11-maktab','53-maktab','53-maktab','53-maktab','53-maktab','maktabga kirmagan','53-maktab','11-maktab'],
    "JINSI":[ 'o`g`il bola','qiz bola','o`g`il','qiz','o`g`il','o`g`il','qiz','o`g`il','o`g`il','qiz' ],
    "MALZIL":[ 'Farg`ona','Farg`ona','Farg`ona','Farg`ona','Farg`ona','Farg`ona','Farg`ona','Farg`ona','farg`ona','farg`ona' ],
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db[ "MAKTABI"]=='11-maktab']
print(filtr)

"""# Новый раздел"""